name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Write settings.xml
        run: echo "<settings><servers><server><id>central</id><username>$MAVEN_CENTRAL_TOKEN_USERNAME</username><password>$MAVEN_CENTRAL_TOKEN_PASSWORD</password></server></servers></settings>" > /home/runner/.m2/settings.xml
        env:
          MAVEN_CENTRAL_TOKEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
      - name: Configure GPG Key
        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import --pinentry-mode loopback --passphrase "$GPG_SIGNING_KEY_PASSWORD"
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      - name: Publish to Maven Central
        run: mvn -P release clean deploy -Dgpg.passphrase="$GPG_SIGNING_KEY_PASSWORD"
        env:
          GPG_SIGNING_KEY_PASSWORD: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
      - name: Create Github release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: |
            ./target/keycloak-hsm-*
          body: |
            **This Github draft release has been created.**